import type { PlayerStats, Position } from '../types/game';

export type ItemCategory = 'equipment' | 'recovery' | 'training' | 'special' | 'realestate' | 'vehicle' | 'entertainment';
export type ItemRarity = 'common' | 'rare' | 'epic' | 'legendary' | 'mythic';

export type ItemEffect = Partial<PlayerStats> & {
  morale?: number;
  fatigue?: number;
  injury?: number;
  fans?: number;
  conductScore?: number;   // 素行スコア変化
  cabaretVisit?: boolean;  // キャバクラカウンタを+1
  addRealEstate?: string;  // 不動産配列に追加するID
  addVehicle?: string;     // 車両配列に追加するID
};

export interface ShopItem {
  id: string;
  name: string;
  description: string;
  icon: string;
  price: number;        // 万円単位
  effect: ItemEffect;
  category: ItemCategory;
  rarity: ItemRarity;
  consumable: boolean;  // true: 何度でも購入可, false: 一度のみ
  forPosition?: Position[];
  requireOvr?: number;
}

export const SHOP_ITEMS: ShopItem[] = [

  // ══ 装備 ══════════════════════════════════════════════════════

  {
    id: 'basic_boots',
    name: 'プロスパイク',
    description: 'シュート精度とスピードが上がる高品質スパイク。',
    icon: '👟',
    price: 50,
    effect: { shooting: 8, speed: 4 },
    category: 'equipment',
    rarity: 'common',
    consumable: false,
    forPosition: ['FW', 'MF'],
  },
  {
    id: 'basic_shin_guard',
    name: 'プロシンガード',
    description: '守備力と怪我リスク軽減。',
    icon: '🛡️',
    price: 60,
    effect: { defense: 8, injury: -3 },
    category: 'equipment',
    rarity: 'common',
    consumable: false,
    forPosition: ['DF', 'MF'],
  },
  {
    id: 'basic_gk_gloves',
    name: 'プロGKグローブ',
    description: 'セービング力と反応速度が向上するGK専用グローブ。',
    icon: '🧤',
    price: 80,
    effect: { defense: 8, stamina: 5 },
    category: 'equipment',
    rarity: 'common',
    consumable: false,
    forPosition: ['GK'],
  },
  {
    id: 'captain_band',
    name: 'キャプテンマーク',
    description: 'チームリーダーとして存在感が増す。',
    icon: '🏅',
    price: 150,
    effect: { morale: 20, fans: 500 },
    category: 'equipment',
    rarity: 'common',
    consumable: false,
    requireOvr: 70,
  },
  {
    id: 'elite_boots',
    name: 'エリートスパイク',
    description: '世界トップ選手も愛用する高性能スパイク。攻撃・突破力を大幅強化。',
    icon: '⚡',
    price: 800,
    effect: { shooting: 25, speed: 12, dribbling: 15 },
    category: 'equipment',
    rarity: 'rare',
    consumable: false,
    requireOvr: 65,
    forPosition: ['FW', 'MF'],
  },
  {
    id: 'elite_shin_guard',
    name: 'エリートシンガード',
    description: '超硬度素材で守備と耐久力を大幅強化。怪我リスクも大幅減。',
    icon: '⚔️',
    price: 600,
    effect: { defense: 30, stamina: 10, injury: -5 },
    category: 'equipment',
    rarity: 'rare',
    consumable: false,
    requireOvr: 65,
    forPosition: ['DF', 'MF'],
  },
  {
    id: 'elite_gk_gloves',
    name: 'エリートGKグローブ',
    description: '欧州トップGKが使用する最高峰グローブ。反応速度が段違い。',
    icon: '🥊',
    price: 700,
    effect: { defense: 30, stamina: 15 },
    category: 'equipment',
    rarity: 'rare',
    consumable: false,
    requireOvr: 65,
    forPosition: ['GK'],
  },
  {
    id: 'champ_boots',
    name: 'チャンピオンズブーツ',
    description: 'チャンピオンズリーグ仕様の超高性能スパイク。別次元の攻撃力。',
    icon: '🔥',
    price: 8000,
    effect: { shooting: 70, speed: 35, dribbling: 50 },
    category: 'equipment',
    rarity: 'epic',
    consumable: false,
    requireOvr: 80,
    forPosition: ['FW', 'MF'],
  },
  {
    id: 'iron_armor',
    name: '鉄壁アーマー',
    description: '最先端素材で造られた究極の防護装備。鉄のような守備力。',
    icon: '🏰',
    price: 7000,
    effect: { defense: 80, stamina: 30, injury: -8 },
    category: 'equipment',
    rarity: 'epic',
    consumable: false,
    requireOvr: 80,
    forPosition: ['DF', 'GK'],
  },
  {
    id: 'golden_gloves',
    name: 'ゴールデングローブ',
    description: '黄金の守護神にふさわしいGK用最高級グローブ。',
    icon: '🥅',
    price: 8000,
    effect: { defense: 90, stamina: 35 },
    category: 'equipment',
    rarity: 'epic',
    consumable: false,
    requireOvr: 80,
    forPosition: ['GK'],
  },
  {
    id: 'legend_boots',
    name: '伝説のスパイク',
    description: '歴史に名を残す選手だけが手にできる伝説の一足。',
    icon: '👑',
    price: 40000,
    effect: { shooting: 150, speed: 80, dribbling: 100 },
    category: 'equipment',
    rarity: 'legendary',
    consumable: false,
    requireOvr: 90,
    forPosition: ['FW', 'MF'],
  },
  {
    id: 'legend_armor',
    name: '伝説の守護壁',
    description: '伝説の守護者だけが身に着けることを許される聖なる装備。',
    icon: '🌟',
    price: 38000,
    effect: { defense: 180, stamina: 70, injury: -12 },
    category: 'equipment',
    rarity: 'legendary',
    consumable: false,
    requireOvr: 90,
    forPosition: ['DF', 'GK'],
  },
  {
    id: 'golden_captain',
    name: '黄金のキャプテンマーク',
    description: '最強のキャプテンに与えられる黄金の腕章。チームを新たな高みへ。',
    icon: '🏆',
    price: 8000,
    effect: { morale: 80, fans: 10000 },
    category: 'equipment',
    rarity: 'epic',
    consumable: false,
    requireOvr: 88,
  },
  {
    id: 'god_boots',
    name: '神の蹴撃',
    description: '神話の域に達した選手だけが着用を許される、この世ならざる一足。',
    icon: '✨',
    price: 150000,
    effect: { shooting: 280, speed: 150, dribbling: 180 },
    category: 'equipment',
    rarity: 'mythic',
    consumable: false,
    requireOvr: 96,
    forPosition: ['FW', 'MF'],
  },
  {
    id: 'god_armor',
    name: '不滅の守護神',
    description: '神域の守備力を持つ選手のみに許される、究極の守護装備。',
    icon: '🔰',
    price: 140000,
    effect: { defense: 320, stamina: 150, injury: -20 },
    category: 'equipment',
    rarity: 'mythic',
    consumable: false,
    requireOvr: 96,
    forPosition: ['DF', 'GK'],
  },

  // ══ 回復 ══════════════════════════════════════════════════════

  {
    id: 'energy_drink',
    name: 'エナジードリンク',
    description: '疲労を素早く回復し、気分もリフレッシュ。',
    icon: '🥤',
    price: 10,
    effect: { fatigue: -25, morale: 5 },
    category: 'recovery',
    rarity: 'common',
    consumable: true,
  },
  {
    id: 'ice_bath',
    name: 'アイスバス',
    description: '激しい疲労と軽い怪我を同時に回復する。',
    icon: '🧊',
    price: 30,
    effect: { fatigue: -50, injury: -3 },
    category: 'recovery',
    rarity: 'common',
    consumable: true,
  },
  {
    id: 'massage',
    name: 'プロマッサージ',
    description: '専属マッサージ師による本格ケア。疲労・怪我・モラル全回復。',
    icon: '💆',
    price: 50,
    effect: { fatigue: -70, morale: 15, injury: -2 },
    category: 'recovery',
    rarity: 'rare',
    consumable: true,
  },
  {
    id: 'sports_medicine',
    name: 'スポーツ医学ケア',
    description: '最新スポーツ医学に基づく徹底ケア。重傷も大幅回復。',
    icon: '🏥',
    price: 200,
    effect: { fatigue: -90, injury: -10, morale: 15 },
    category: 'recovery',
    rarity: 'rare',
    consumable: true,
    requireOvr: 70,
  },
  {
    id: 'personal_doctor',
    name: '専属ドクター',
    description: '世界最高峰の専属医によるVIPケア。完全回復を保証する。',
    icon: '👨‍⚕️',
    price: 1000,
    effect: { fatigue: -100, injury: -20, morale: 30 },
    category: 'recovery',
    rarity: 'epic',
    consumable: true,
    requireOvr: 80,
  },
  {
    id: 'miracle_recovery',
    name: '奇跡の回復薬',
    description: '伝説の調合師が造った極秘の回復薬。全ての疲労と怪我を消し去る。',
    icon: '💊',
    price: 5000,
    effect: { fatigue: -100, injury: -30, morale: 50 },
    category: 'recovery',
    rarity: 'legendary',
    consumable: true,
    requireOvr: 88,
  },

  // ══ トレーニング ═══════════════════════════════════════════════

  {
    id: 'protein',
    name: 'プロテイン',
    description: 'スタミナと体力を強化する栄養補助食品。',
    icon: '💪',
    price: 40,
    effect: { stamina: 12 },
    category: 'training',
    rarity: 'common',
    consumable: false,
  },
  {
    id: 'training_video',
    name: 'トレーニング映像',
    description: '元代表コーチによるパス分析映像。パス精度向上。',
    icon: '📹',
    price: 70,
    effect: { passing: 12 },
    category: 'training',
    rarity: 'common',
    consumable: false,
  },
  {
    id: 'nutritionist',
    name: '専属栄養士',
    description: '最適な食事管理でスタミナとスピードを底上げ。',
    icon: '🥗',
    price: 300,
    effect: { stamina: 20, speed: 12 },
    category: 'training',
    rarity: 'rare',
    consumable: false,
    requireOvr: 60,
  },
  {
    id: 'specialist_shooting',
    name: 'シュート特化訓練',
    description: '元トップストライカーによる一対一指導。シュート力が激増。',
    icon: '🎯',
    price: 1000,
    effect: { shooting: 40 },
    category: 'training',
    rarity: 'rare',
    consumable: false,
    requireOvr: 68,
    forPosition: ['FW', 'MF'],
  },
  {
    id: 'specialist_dribbling',
    name: 'ドリブル特化訓練',
    description: '元ドリブラーによる徹底指導。突破力が格段に向上。',
    icon: '🕺',
    price: 1000,
    effect: { dribbling: 40 },
    category: 'training',
    rarity: 'rare',
    consumable: false,
    requireOvr: 68,
    forPosition: ['FW', 'MF'],
  },
  {
    id: 'specialist_defense',
    name: '守備特化訓練',
    description: '元名DFによる守備の極意伝授。守備力が大幅アップ。',
    icon: '🛡️',
    price: 1000,
    effect: { defense: 40 },
    category: 'training',
    rarity: 'rare',
    consumable: false,
    requireOvr: 68,
    forPosition: ['DF', 'GK'],
  },
  {
    id: 'vip_training',
    name: 'VIPトレーニング',
    description: '元プロ選手によるマンツーマン全面指導。全能力が大幅アップ。',
    icon: '⭐',
    price: 1200,
    effect: { shooting: 15, passing: 15, dribbling: 15, speed: 12, stamina: 12, defense: 12 },
    category: 'training',
    rarity: 'rare',
    consumable: false,
    requireOvr: 72,
  },
  {
    id: 'elite_academy',
    name: 'エリートアカデミー',
    description: '欧州最高峰アカデミーへの短期留学。全スタットが爆発的に向上。',
    icon: '🏫',
    price: 15000,
    effect: { shooting: 70, passing: 70, dribbling: 70, speed: 55, stamina: 55, defense: 55 },
    category: 'training',
    rarity: 'epic',
    consumable: false,
    requireOvr: 82,
  },
  {
    id: 'world_class_coach',
    name: '世界最高指導者',
    description: '伝説の監督による秘密特訓。その教えは選手の本質を変える。',
    icon: '🧙',
    price: 60000,
    effect: { shooting: 140, passing: 140, dribbling: 140, speed: 110, stamina: 110, defense: 110 },
    category: 'training',
    rarity: 'legendary',
    consumable: false,
    requireOvr: 90,
  },
  {
    id: 'limit_break_fw',
    name: '限界突破：攻撃神化',
    description: '人間の限界を超えた攻撃能力の覚醒。FW専用の究極特訓。',
    icon: '💥',
    price: 120000,
    effect: { shooting: 250, dribbling: 200, speed: 180 },
    category: 'training',
    rarity: 'mythic',
    consumable: false,
    requireOvr: 95,
    forPosition: ['FW'],
  },
  {
    id: 'limit_break_def',
    name: '限界突破：守護神化',
    description: '守備能力の極限を超えた神域の覚醒。DF/GK専用の究極特訓。',
    icon: '🌊',
    price: 120000,
    effect: { defense: 300, stamina: 200 },
    category: 'training',
    rarity: 'mythic',
    consumable: false,
    requireOvr: 95,
    forPosition: ['DF', 'GK'],
  },
  {
    id: 'limit_break_all',
    name: '限界突破：完全覚醒',
    description: 'あらゆる能力の限界を超える、最後の扉を開く儀式。',
    icon: '🌌',
    price: 200000,
    effect: { shooting: 180, passing: 180, dribbling: 180, speed: 150, stamina: 150, defense: 150 },
    category: 'training',
    rarity: 'mythic',
    consumable: false,
    requireOvr: 97,
  },

  // ══ スペシャル ═════════════════════════════════════════════════

  {
    id: 'fan_event',
    name: 'ファンイベント',
    description: 'ファンイベントを開催してサポーターが急増。',
    icon: '🎉',
    price: 80,
    effect: { fans: 1500, morale: 10 },
    category: 'special',
    rarity: 'common',
    consumable: true,
  },
  {
    id: 'mental_coach',
    name: 'メンタルコーチ',
    description: 'メンタル強化セッションでモラルが大幅回復。',
    icon: '🧠',
    price: 120,
    effect: { morale: 50 },
    category: 'special',
    rarity: 'common',
    consumable: false,
  },
  {
    id: 'sports_agent',
    name: 'スポーツエージェント',
    description: 'エージェント契約でファン数増加と影響力アップ。',
    icon: '🤝',
    price: 500,
    effect: { fans: 5000, morale: 20 },
    category: 'special',
    rarity: 'rare',
    consumable: false,
    requireOvr: 72,
  },
  {
    id: 'sns_campaign',
    name: 'SNSキャンペーン',
    description: 'グローバルSNS戦略でファン層が爆発的拡大。',
    icon: '📱',
    price: 600,
    effect: { fans: 8000, morale: 15 },
    category: 'special',
    rarity: 'rare',
    consumable: true,
    requireOvr: 75,
  },
  {
    id: 'media_exposure',
    name: '国際メディア露出',
    description: '欧米メディアに大々的に特集される。世界中にファンが増加。',
    icon: '📺',
    price: 5000,
    effect: { fans: 30000, morale: 30 },
    category: 'special',
    rarity: 'epic',
    consumable: true,
    requireOvr: 82,
  },
  {
    id: 'global_star',
    name: 'グローバルスター',
    description: '世界的スターの称号を得る。ファンが全大陸から集まる。',
    icon: '🌍',
    price: 35000,
    effect: { fans: 100000, morale: 60 },
    category: 'special',
    rarity: 'legendary',
    consumable: false,
    requireOvr: 92,
  },
  // ══ 不動産 (Real Estate) ═══════════════════════════════════

  {
    id: 're_myhome',
    name: 'マイホーム購入',
    description: '念願のマイホームを手に入れた。家族も喜んでいる。',
    icon: '🏠',
    price: 500,
    effect: { morale: 15, conductScore: 5, addRealEstate: 're_myhome' },
    category: 'realestate',
    rarity: 'common',
    consumable: false,
  },
  {
    id: 're_luxury_apt',
    name: '高級マンション',
    description: '都心の高層マンションを購入。眺望が素晴らしい。',
    icon: '🏙️',
    price: 5000,
    effect: { morale: 25, conductScore: 3, fans: 2000, addRealEstate: 're_luxury_apt' },
    category: 'realestate',
    rarity: 'rare',
    consumable: false,
    requireOvr: 70,
  },
  {
    id: 're_tower',
    name: 'タワーマンション最上階',
    description: '最高層の億ションを手に入れた。ここが俺の城だ。',
    icon: '🗼',
    price: 20000,
    effect: { morale: 35, conductScore: 5, fans: 10000, addRealEstate: 're_tower' },
    category: 'realestate',
    rarity: 'epic',
    consumable: false,
    requireOvr: 82,
  },
  {
    id: 're_mansion',
    name: '豪邸',
    description: '広大な敷地に建つ豪邸。プール付きの夢の邸宅を所有した。',
    icon: '🏯',
    price: 50000,
    effect: { morale: 45, conductScore: 8, fans: 30000, addRealEstate: 're_mansion' },
    category: 'realestate',
    rarity: 'legendary',
    consumable: false,
    requireOvr: 90,
  },
  {
    id: 're_resort',
    name: 'リゾート別荘',
    description: '南国のリゾート地に別荘を購入。オフシーズンの完全リカバリー地。',
    icon: '🏝️',
    price: 120000,
    effect: { morale: 60, conductScore: 10, fans: 50000, stamina: 20, addRealEstate: 're_resort' },
    category: 'realestate',
    rarity: 'mythic',
    consumable: false,
    requireOvr: 95,
  },

  // ══ 車両 (Vehicle) ═══════════════════════════════════════

  {
    id: 'car_sedan',
    name: 'セダン購入',
    description: '初めての愛車。通勤も練習場への移動も快適になった。',
    icon: '🚗',
    price: 200,
    effect: { morale: 10, conductScore: 2, addVehicle: 'car_sedan' },
    category: 'vehicle',
    rarity: 'common',
    consumable: false,
  },
  {
    id: 'car_sports',
    name: 'スポーツカー',
    description: '週末のドライブが楽しみになった。スタイリッシュな一台。',
    icon: '🏎️',
    price: 2000,
    effect: { morale: 20, fans: 3000, conductScore: 2, addVehicle: 'car_sports' },
    category: 'vehicle',
    rarity: 'rare',
    consumable: false,
    requireOvr: 68,
  },
  {
    id: 'car_foreign_luxury',
    name: '外国産ラグジュアリーカー',
    description: 'ドイツ製高級車。チームメイトに自慢できる一台。',
    icon: '🚙',
    price: 8000,
    effect: { morale: 30, fans: 8000, conductScore: 3, addVehicle: 'car_foreign_luxury' },
    category: 'vehicle',
    rarity: 'epic',
    consumable: false,
    requireOvr: 80,
  },
  {
    id: 'car_supercar',
    name: 'スーパーカー',
    description: '世界限定モデルのスーパーカー。SNSで大バズり確定。',
    icon: '⚡',
    price: 30000,
    effect: { morale: 40, fans: 25000, conductScore: 2, addVehicle: 'car_supercar' },
    category: 'vehicle',
    rarity: 'legendary',
    consumable: false,
    requireOvr: 88,
  },
  {
    id: 'car_hypercar',
    name: '世界限定ハイパーカー',
    description: '世界に10台しかない伝説の超高級車。所有するだけで伝説になれる。',
    icon: '🌟',
    price: 100000,
    effect: { morale: 55, fans: 80000, conductScore: 3, addVehicle: 'car_hypercar' },
    category: 'vehicle',
    rarity: 'mythic',
    consumable: false,
    requireOvr: 95,
  },

  // ══ 遊興 (Entertainment) ══════════════════════════════════
  // 繰り返し利用でペナルティが累積する

  {
    id: 'ent_cabaret',
    name: 'キャバクラ',
    description: '⚠️ 一時的なモラル回復。しかし訪問回数が増えるほどペナルティが蓄積する。',
    icon: '🍸',
    price: 50,
    effect: { morale: 20, fatigue: -10, conductScore: -8, cabaretVisit: true },
    category: 'entertainment',
    rarity: 'common',
    consumable: true,
  },
  {
    id: 'ent_vip_cabaret',
    name: 'VIPキャバクラ',
    description: '⚠️ 高級店で豪遊。財布と素行に大きなダメージを残す。',
    icon: '💎',
    price: 200,
    effect: { morale: 30, fatigue: -20, conductScore: -15, cabaretVisit: true },
    category: 'entertainment',
    rarity: 'rare',
    consumable: true,
  },
  {
    id: 'ent_ultra_club',
    name: '超高級クラブ',
    description: '⚠️⚠️ 1回で数百万が消える夜。モラルは上がるが代償は計り知れない。',
    icon: '🥂',
    price: 1000,
    effect: { morale: 40, fatigue: -25, conductScore: -25, cabaretVisit: true },
    category: 'entertainment',
    rarity: 'epic',
    consumable: true,
  },

  {
    id: 'living_legend',
    name: '生ける伝説',
    description: '歴史に刻まれた生ける伝説。その存在だけで世界が揺れる。',
    icon: '🌠',
    price: 100000,
    effect: { fans: 500000, morale: 100 },
    category: 'special',
    rarity: 'mythic',
    consumable: false,
    requireOvr: 97,
  },
];

export const CATEGORY_LABEL: Record<ItemCategory, string> = {
  equipment:     '装備',
  recovery:      '回復',
  training:      'トレーニング',
  special:       'スペシャル',
  realestate:    '不動産',
  vehicle:       '車両',
  entertainment: '⚠️遊興',
};

export const CATEGORY_ICON: Record<ItemCategory, string> = {
  equipment:     '⚙️',
  recovery:      '❤️‍🩹',
  training:      '🏋️',
  special:       '✨',
  realestate:    '🏠',
  vehicle:       '🚗',
  entertainment: '🍸',
};

export const RARITY_LABEL: Record<ItemRarity, string> = {
  common:    'コモン',
  rare:      'レア',
  epic:      'エピック',
  legendary: 'レジェンド',
  mythic:    'ミシック',
};

export const RARITY_COLOR: Record<ItemRarity, string> = {
  common:    '#9ca3af',
  rare:      '#3b82f6',
  epic:      '#a855f7',
  legendary: '#eab308',
  mythic:    '#ef4444',
};
